// Generated by gencpp from file vpa_host/AssignTask.msg
// DO NOT EDIT!


#ifndef VPA_HOST_MESSAGE_ASSIGNTASK_H
#define VPA_HOST_MESSAGE_ASSIGNTASK_H

#include <ros/service_traits.h>


#include <vpa_host/AssignTaskRequest.h>
#include <vpa_host/AssignTaskResponse.h>


namespace vpa_host
{

struct AssignTask
{

typedef AssignTaskRequest Request;
typedef AssignTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AssignTask
} // namespace vpa_host


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vpa_host::AssignTask > {
  static const char* value()
  {
    return "cdad0eb519e23dd2b5d3e4c2e2b7ecf6";
  }

  static const char* value(const ::vpa_host::AssignTask&) { return value(); }
};

template<>
struct DataType< ::vpa_host::AssignTask > {
  static const char* value()
  {
    return "vpa_host/AssignTask";
  }

  static const char* value(const ::vpa_host::AssignTask&) { return value(); }
};


// service_traits::MD5Sum< ::vpa_host::AssignTaskRequest> should match
// service_traits::MD5Sum< ::vpa_host::AssignTask >
template<>
struct MD5Sum< ::vpa_host::AssignTaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vpa_host::AssignTask >::value();
  }
  static const char* value(const ::vpa_host::AssignTaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vpa_host::AssignTaskRequest> should match
// service_traits::DataType< ::vpa_host::AssignTask >
template<>
struct DataType< ::vpa_host::AssignTaskRequest>
{
  static const char* value()
  {
    return DataType< ::vpa_host::AssignTask >::value();
  }
  static const char* value(const ::vpa_host::AssignTaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vpa_host::AssignTaskResponse> should match
// service_traits::MD5Sum< ::vpa_host::AssignTask >
template<>
struct MD5Sum< ::vpa_host::AssignTaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vpa_host::AssignTask >::value();
  }
  static const char* value(const ::vpa_host::AssignTaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vpa_host::AssignTaskResponse> should match
// service_traits::DataType< ::vpa_host::AssignTask >
template<>
struct DataType< ::vpa_host::AssignTaskResponse>
{
  static const char* value()
  {
    return DataType< ::vpa_host::AssignTask >::value();
  }
  static const char* value(const ::vpa_host::AssignTaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VPA_HOST_MESSAGE_ASSIGNTASK_H
